"""Renders a Report (daily/morning/weekly brief) to a downloadable PDF.

Reports are already structured, section-based JSON (see ReportService) — this just lays that
same content out on a page, so "give me a PDF at the end" is backed by the real aggregated data,
never a fabricated summary.
"""

from __future__ import annotations

from fpdf import FPDF

from app.models.report import Report

_SECTION_TITLES = {
    "needs_you": "Needs your attention",
    "important_discoveries": "Important discoveries",
    "deep_work_completed": "Deep work completed",
    "new_tasks": "New tasks",
}


def render_report_pdf(report: Report) -> bytes:
    pdf = FPDF(unit="mm", format="A4")
    pdf.set_auto_page_break(auto=True, margin=18)
    pdf.add_page()

    pdf.set_font("Helvetica", "B", 18)
    pdf.multi_cell(0, 10, _latin1(report.title), new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(110, 110, 110)
    range_label = ""
    if report.range_start and report.range_end:
        range_label = f"{report.range_start:%b %d, %Y} – {report.range_end:%b %d, %Y}"
    pdf.cell(0, 6, _latin1(f"Generated by {report.generated_by}   {range_label}"), new_x="LMARGIN", new_y="NEXT")
    pdf.set_text_color(0, 0, 0)
    pdf.ln(4)

    content = report.content or {}

    headline = content.get("headline")
    if headline:
        _section_heading(pdf, "Summary")
        pdf.set_font("Helvetica", "", 11)
        for key, value in headline.items():
            label = key.replace("_", " ").capitalize()
            pdf.cell(0, 7, _latin1(f"  - {label}: {value}"), new_x="LMARGIN", new_y="NEXT")
        pdf.ln(2)

    for key, title in _SECTION_TITLES.items():
        items = content.get(key) or []
        if not items:
            continue
        _section_heading(pdf, title)
        pdf.set_font("Helvetica", "", 11)
        for item in items:
            label = item.get("label", "") if isinstance(item, dict) else str(item)
            pdf.multi_cell(0, 6, _latin1(f"  - {label}"), new_x="LMARGIN", new_y="NEXT")
        pdf.ln(2)

    if content.get("memory_changes") is not None:
        pdf.set_font("Helvetica", "I", 10)
        pdf.set_text_color(110, 110, 110)
        pdf.cell(0, 6, _latin1(f"{content['memory_changes']} memory update(s) this period."))
        pdf.set_text_color(0, 0, 0)

    return bytes(pdf.output())


def _section_heading(pdf: FPDF, title: str) -> None:
    pdf.set_font("Helvetica", "B", 13)
    pdf.set_fill_color(240, 240, 245)
    pdf.cell(0, 9, _latin1(f" {title}"), new_x="LMARGIN", new_y="NEXT", fill=True)
    pdf.ln(1)


_PUNCT_MAP = str.maketrans({
    "—": "-", "–": "-",  # em/en dash
    "‘": "'", "’": "'",  # curly single quotes
    "“": '"', "”": '"',  # curly double quotes
    "…": "...",  # ellipsis
})


def _latin1(text: str) -> str:
    # Core Helvetica font only supports latin-1 — normalize common smart punctuation to its ASCII
    # equivalent first so it reads cleanly instead of degrading to "?".
    return text.translate(_PUNCT_MAP).encode("latin-1", "replace").decode("latin-1")
