"""initial schema

Creates the pgvector extension (if available) and all Council tables from the SQLAlchemy metadata.

We intentionally build the schema from `Base.metadata` rather than hand-writing every column: the
ORM models are the single source of truth, and this keeps the first migration in lockstep with
them. Subsequent schema changes should use autogenerated incremental migrations.

Revision ID: 0001_initial
Revises:
Create Date: 2026-01-01
"""
from __future__ import annotations

from alembic import op

from app.db.base import Base
from app.models import *  # noqa: F401,F403 — register all tables on metadata

revision = "0001_initial"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    bind = op.get_bind()
    # Enable pgvector where supported (safe no-op elsewhere / already enabled).
    try:
        op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    except Exception:
        pass
    Base.metadata.create_all(bind=bind)


def downgrade() -> None:
    bind = op.get_bind()
    Base.metadata.drop_all(bind=bind)
